.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IOT" "1" "January 2011" "SCHEIBO" "iot Manual"
.
.SH "NAME"
\fBiot\fR \- input output test
.
.SH "SYNOPSIS"
\fBiot\fR \fIprogram\fR \fItest\fR\.\.\.
.
.br
\fBiot\fR \fIprogram\fR \fIsuite\fR\.\.\.
.
.br
.
.SH "DESCRIPTION"
\fBiot\fR serves as a testing \'suite\' for the times when you only care that given a certain input, a certain output is produced\. \fBiot\fR tries to be a simple solution to creating and managing test suites in this limited environment\.
.
.P
The basic idea behind \fBiot\fR is that it runs a given program and saves the output (and error) streams, comparing them to the expected output (and error)\. \fBiot\fR can handle running entire suites of such tests (i\.e\. directories on input files), or simply individual tests\. One powerful feature that \fBiot\fR has is the ability to accept custom matchers for dealing with the output of tests\. See the \'Custom Test Matchers\' section below for more information\.
.
.IP "\(bu" 4
view the README \fIhttps://github\.com/scheibo/iot#readme\fR\.
.
.IP "\(bu" 4
view the annotated source \fIhttp://scheibo\.github\.com/iot\fR\.
.
.IP "" 0
.
.SH "USAGE"
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat\. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur\. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\.
.
.P
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat\. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur\. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\.
.
.SH "OPTIONS"
The following elements specify directory or file preferences\. These values can also be set by via the [ENVIRONMENT][]\.
.
.TP
\fB\-r\fR, \fB\-\-rootdir\fR,\fB\-\-rootdir\fR=\fIdirectory\fR
The directory which contains the top level \'test\' directory\.
.
.TP
\fB\-t\fR \fIdirectory\fR, \fB\-\-tempdir\fR \fIdirectory\fR, \fB\-\-tempdir\fR=\fIdirectory\fR, \fB\-s\fR \fIdirectory\fR, \fB\-\-sandboxdir\fR \fIdirectory\fR, \fB\-\-sandboxdir\fR=\fIdirectory\fR
The directory to store all of \fBiot\fR\'s temporary files\.
.
.TP
\fB\-c\fR \fIfile\fR, \fB\-\-command\fR \fIfile\fR, \fB\-\-command\fR=\fIfile\fR
Use the given command to execute the \fIprogram\fR which is being tested as opposed to running it with \fB\./program\fR
.
.TP
\fB\-m\fR, \fB\-\-matcher\fR \fIfile\fR
Path to a custom \fImatcher\fR file\.
.
.P
Various different mode options can also be specified:
.
.TP
\fB\-i\fR, \fB\-\-immeadiate\fR
Immediately print diagnostic information regarding each failed test as opposed to waiting until all the tests have been run\.
.
.TP
\fB\-x\fR, \fB\-\-sudden\-death\fR
Stop testing after the first failed test\. Immediately exit and print information regarding the failed test case\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Don\'t print any output, just return an exit code signaling pass or fail\.
.
.SH "ENVIRONMENT_VARIABLES"
.
.TP
\fBROOTDIR\fR
The directory which contains the top level \'test\' directory\. The \fB\-\-rootdir\fR option takes precedence over this value\.
.
.TP
\fBSANDBOXDIR\fR
The directory which contains the top level \'test\' directory\. The \fB\-\-sandboxdir\fR option takes precedence over this value\.
.
.TP
\fBCOMMAND\fR
Use the given command to execute the \fIprogram\fR which is being tested as opposed to running it with \fB\./program\fR\. The \fB\-\-command\fR option takes precedence over this value\.
.
.TP
\fBMATCHER_FILE\fR
Path to a custom \fImatcher\fR file\. The \fB\-\-matcher\fR option takes precedence over this value\.
.
.SH "CUSTOM MATCHERS"
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat\. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur\. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\.
.
.P
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua\. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat\. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur\. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\.
.
.SH "RETURN VALUES"
\fBiot\fR returns the number of tests which failed as its exit code\.
.
.SH "SECURITY CONSIDERATIONS"
Since \fBeval\fR is used, potentially arbitrary bits of code can be executed\. The best way to avoid this potential security hole is to be somewhat intelligent when using \fBiot\fR\. Running it as root or with things like \'rm \-rf\' as a command argument are bound for trouble, and to be fair, you probably deserve to get shot in the foot if you plan on using it like that\.
.
.SH "BUGS"
Please open up an issue \fIhttps://github\.com/scheibo/iot/issues\fR on Github if you find a bug\. Patches and pull requests are always welcome\.
.
.SH "COPYRIGHT"
\fBiot\fR is Copyright (C) 2011 Kirk Scheibelhut http://scheibo\.com/about
